name: test-release
on:
  push:
    tags:
      - v*
defaults:
  run:
    working-directory: python
jobs:
  test:
    name: Running the Python test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
      - name: Run
        env:
          API_KEY: ${{ secrets.DEV_API_KEY }}
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
          API_HOST: https://api.lfmdev.in
          AUTH_HOST: https://auth.lfmdev.in
        run: |
          python3 setup.py pytest

  upload-test-pypi:
    name: Uploading to Test PyPI
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine setuptools wheel
      - name: Build distribution
        run: python3 -m build
      - name: Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: python3 -m twine upload -r testpypi dist/*
